version: 2.1

orbs:
  node: circleci/node@5.2

workflows:
  test_lib: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - node/test:
          version: "21.6"
          pkg-manager: npm
          filters:
            tags:
              only: /^v.*/
