version: 2.1

orbs:
  node: circleci/node@7.1

workflows:
  test_lib:
    jobs:
      - node/test:
          version: "21.6"
          pkg-manager: npm
          filters:
            tags:
              only: /^v.*/
